import type {Metadata} from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Store-Me Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={` bg-white flex flex-col min-h-full antialiased`}
      >
        <Navbar />
        <main className=" container mx-auto px-4 py-8 ">
          {children}
        </main>
      </body>
    </html>
  );
}
